// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Unach.DA.Empleo.Persistencia.Core.Models
{
    public partial class EstadoPostulacion
    {
        [Key]
        public int Id { get; set; }
        public int IdPostulacion { get; set; }
        [Required]
        [StringLength(50)]
        public string IdEstadoPostulacion { get; set; }
        [Required]
        [StringLength(100)]
        public string IdUsuarioAudd { get; set; }
        [Required]
        public string RolAudd { get; set; }
        [Required]
        [StringLength(50)]
        public string DireccionIpAudd { get; set; }
        [Required]
        [StringLength(250)]
        public string SistemaAudd { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaTransaccion { get; set; }

        [ForeignKey("IdEstadoPostulacion")]
        [InverseProperty("EstadoPostulacion")]
        public virtual TipoEstadoPostulacion IdEstadoPostulacionNavigation { get; set; }
        [ForeignKey("IdPostulacion")]
        [InverseProperty("EstadoPostulacion")]
        public virtual Postulacion IdPostulacionNavigation { get; set; }
    }
}