// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Unach.DA.Empleo.Persistencia.Core.Models
{
    public partial class Estudiante
    {
        public int IdEstudiante { get; set; }
        [Required]
        [StringLength(100)]
        public string IdUsuarioAudd { get; set; }
        [Required]
        public string RolAudd { get; set; }
        [Required]
        [StringLength(50)]
        public string DireccionIpAudd { get; set; }
        [Required]
        [StringLength(250)]
        public string SistemaAudd { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaTransaccion { get; set; }
        [Key]
        public string Id { get; set; }
        public string LinkLinkeding { get; set; }

        [InverseProperty("IdNavigation")]
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}