// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Unach.DA.Empleo.Persistencia.Core.Models
{
    public partial class FormacionAcademica
    {
        [Key]
        public int Id { get; set; }
        public int IdFormacionAcademica { get; set; }
        public int IdEstudiante { get; set; }
        [Required]
        [StringLength(50)]
        public string Descripcion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaIncio { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaFin { get; set; }
        [Required]
        public string Certificado { get; set; }
        [Required]
        [StringLength(100)]
        public string IdUsuarioAudd { get; set; }
        [Required]
        public string RolAudd { get; set; }
        [Required]
        [StringLength(50)]
        public string DireccionlpAudd { get; set; }
        [Required]
        [StringLength(250)]
        public string SistemaAudd { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaTransaccion { get; set; }

        [ForeignKey("IdEstudiante")]
        [InverseProperty("FormacionAcademica")]
        public virtual Estudiante IdEstudianteNavigation { get; set; }
        [ForeignKey("IdFormacionAcademica")]
        [InverseProperty("FormacionAcademica")]
        public virtual TipoFormacionAcademica IdFormacionAcademicaNavigation { get; set; }
    }
}