// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Unach.DA.Empleo.Persistencia.Core.Models
{
    public partial class Logro
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(250)]
        public string Descripcion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaInicio { get; set; }
        public int IdLogro { get; set; }
        [Required]
        [StringLength(450)]
        public string IdEstudiante { get; set; }
        [Required]
        [StringLength(50)]
        public string Institucion { get; set; }
        [Required]
        public string Certificado { get; set; }
        [Required]
        [StringLength(100)]
        public string IdUsuarioAudd { get; set; }
        [Required]
        public string RolAudd { get; set; }
        [Required]
        [StringLength(50)]
        public string DireccionIpAudd { get; set; }
        [Required]
        [StringLength(250)]
        public string SistemaAudd { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaTransaccion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaFin { get; set; }

        [ForeignKey("IdEstudiante")]
        [InverseProperty("Logro")]
        public virtual Estudiante IdEstudianteNavigation { get; set; }
        [ForeignKey("IdLogro")]
        [InverseProperty("Logro")]
        public virtual TipoLogro IdLogroNavigation { get; set; }
    }
}