// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Unach.DA.Empleo.Persistencia.Core.Models
{
    [Table("Modulo", Schema = "Auth")]
    public partial class Modulo
    {
        public Modulo()
        {
            Transaccion = new HashSet<Transaccion>();
        }

        [Key]
        public int Id { get; set; }
        public int IdSistema { get; set; }
        [Required]
        [StringLength(250)]
        public string Nombre { get; set; }
        [Required]
        public string Descripcion { get; set; }
        [Required]
        [StringLength(15)]
        public string IdUsuarioAudd { get; set; }
        [Required]
        public string RolAudd { get; set; }
        [Required]
        [StringLength(50)]
        public string DireccionIpAudd { get; set; }
        [Required]
        [StringLength(250)]
        public string SistemaAudd { get; set; }

        [ForeignKey("IdSistema")]
        [InverseProperty("Modulo")]
        public virtual Sistema IdSistemaNavigation { get; set; }
        [InverseProperty("IdModuloNavigation")]
        public virtual ICollection<Transaccion> Transaccion { get; set; }
    }
}