// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Unach.DA.Empleo.Persistencia.Core.Models
{
    public partial class Postulacion
    {
        public Postulacion()
        {
            EstadoPostulacion = new HashSet<EstadoPostulacion>();
        }

        [Key]
        public int Id { get; set; }
        public int IdEstudiante { get; set; }
        public int IdVacante { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Fecha { get; set; }
        [Required]
        [StringLength(100)]
        public string IdUsuarioAudd { get; set; }
        [Required]
        public string RolAudd { get; set; }
        [Required]
        [StringLength(50)]
        public string DireccionIpAudd { get; set; }
        [Required]
        [StringLength(250)]
        public string SistemaAudd { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaTransaccion { get; set; }

        [ForeignKey("IdEstudiante")]
        [InverseProperty("Postulacion")]
        public virtual Estudiante IdEstudianteNavigation { get; set; }
        [ForeignKey("IdVacante")]
        [InverseProperty("Postulacion")]
        public virtual Vacante IdVacanteNavigation { get; set; }
        [InverseProperty("IdPostulacionNavigation")]
        public virtual ICollection<EstadoPostulacion> EstadoPostulacion { get; set; }
    }
}