// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Unach.DA.Empleo.Persistencia.Core.Models
{
    public partial class ResponsableEmpresa
    {
        [Key]
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public int IdTipoUsuario { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Fecha { get; set; }
        [StringLength(250)]
        public string Apellido { get; set; }
        [StringLength(250)]
        public string Email { get; set; }
        [StringLength(250)]
        public string Direccion { get; set; }
        [StringLength(250)]
        public string Telefono { get; set; }
        [Required]
        [StringLength(100)]
        public string IdUsuarioAudd { get; set; }
        [Required]
        public string RolAudd { get; set; }
        [Required]
        [StringLength(50)]
        public string DireccionIpAudd { get; set; }
        [Required]
        [StringLength(250)]
        public string SistemaAudd { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaTransaccion { get; set; }
        [StringLength(250)]
        public string Nombre { get; set; }

        [ForeignKey("IdEmpresa")]
        [InverseProperty("ResponsableEmpresa")]
        public virtual Empresa IdEmpresaNavigation { get; set; }
        [ForeignKey("IdTipoUsuario")]
        [InverseProperty("ResponsableEmpresa")]
        public virtual TipoUsuario IdTipoUsuarioNavigation { get; set; }
    }
}