// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Unach.DA.Empleo.Persistencia.Core.Models
{
    [Table("RolTransaccion", Schema = "Auth")]
    public partial class RolTransaccion
    {
        [Key]
        public int IdRol { get; set; }
        [Key]
        public int IdTransaccion { get; set; }
        [Required]
        [StringLength(15)]
        public string IdUsuarioAudd { get; set; }
        [Required]
        public string RolAudd { get; set; }
        [Required]
        [StringLength(50)]
        public string DireccionIpAudd { get; set; }
        [Required]
        [StringLength(250)]
        public string SistemaAudd { get; set; }

        [ForeignKey("IdRol")]
        [InverseProperty("RolTransaccion")]
        public virtual Rol IdRolNavigation { get; set; }
        [ForeignKey("IdTransaccion")]
        [InverseProperty("RolTransaccion")]
        public virtual Transaccion IdTransaccionNavigation { get; set; }
    }
}