// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Unach.DA.Empleo.Persistencia.Core.Models
{
    [Keyless]
    [Table("RolUsuario", Schema = "Auth")]
    public partial class RolUsuario
    {
        public int IdRol { get; set; }
        [Required]
        [StringLength(450)]
        public string IdUsuario { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Desde { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Hasta { get; set; }
        [Required]
        [StringLength(15)]
        public string IdUsuarioAudd { get; set; }
        [Required]
        public string RolAudd { get; set; }
        [Required]
        [StringLength(50)]
        public string DireccionIpAudd { get; set; }
        [Required]
        [StringLength(250)]
        public string SistemaAudd { get; set; }

        [ForeignKey("IdRol")]
        public virtual Rol IdRolNavigation { get; set; }
    }
}