// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Unach.DA.Empleo.Persistencia.Core.Models
{
    public partial class SicoaContext : DbContext
    {
        public SicoaContext()
        {
        }

        public SicoaContext(DbContextOptions<SicoaContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Capacitacion> Capacitacion { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<EstadoPostulacion> EstadoPostulacion { get; set; }
        public virtual DbSet<EstadoVacante> EstadoVacante { get; set; }
        public virtual DbSet<Estudiante> Estudiante { get; set; }
        public virtual DbSet<EstudianteIdioma> EstudianteIdioma { get; set; }
        public virtual DbSet<ExperienciaLaboral> ExperienciaLaboral { get; set; }
        public virtual DbSet<FormacionAcademica> FormacionAcademica { get; set; }
        public virtual DbSet<Idioma> Idioma { get; set; }
        public virtual DbSet<Logro> Logro { get; set; }
        public virtual DbSet<Modulo> Modulo { get; set; }
        public virtual DbSet<Postulacion> Postulacion { get; set; }
        public virtual DbSet<ResponsableEmpresa> ResponsableEmpresa { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<RolTransaccion> RolTransaccion { get; set; }
        public virtual DbSet<RolUsuario> RolUsuario { get; set; }
        public virtual DbSet<Sistema> Sistema { get; set; }
        public virtual DbSet<TipoCapacitacion> TipoCapacitacion { get; set; }
        public virtual DbSet<TipoEstadoPostulacion> TipoEstadoPostulacion { get; set; }
        public virtual DbSet<TipoEstadoVacante> TipoEstadoVacante { get; set; }
        public virtual DbSet<TipoExperiencialaboral> TipoExperiencialaboral { get; set; }
        public virtual DbSet<TipoFormacionAcademica> TipoFormacionAcademica { get; set; }
        public virtual DbSet<TipoLogro> TipoLogro { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<TipoVacante> TipoVacante { get; set; }
        public virtual DbSet<Transaccion> Transaccion { get; set; }
        public virtual DbSet<Vacante> Vacante { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AspNetUsers>(entity =>
            {
                entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
                    .IsUnique()
                    .HasFilter("([NormalizedUserName] IS NOT NULL)");

                entity.HasOne(d => d.IdNavigation)
                    .WithOne(p => p.AspNetUsers)
                    .HasForeignKey<AspNetUsers>(d => d.Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_AspNetUsers_Estudiante");
            });

            modelBuilder.Entity<EstadoPostulacion>(entity =>
            {
                entity.HasOne(d => d.IdEstadoPostulacionNavigation)
                    .WithMany(p => p.EstadoPostulacion)
                    .HasForeignKey(d => d.IdEstadoPostulacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__EstadoPos__IdEst__1EA48E88");

                entity.HasOne(d => d.IdPostulacionNavigation)
                    .WithMany(p => p.EstadoPostulacion)
                    .HasForeignKey(d => d.IdPostulacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__EstadoPos__IdPos__1DB06A4F");
            });

            modelBuilder.Entity<EstadoVacante>(entity =>
            {
                entity.HasOne(d => d.IdEstadoVacanteNavigation)
                    .WithMany(p => p.EstadoVacante)
                    .HasForeignKey(d => d.IdEstadoVacante)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__EstadoVac__IdEst__22751F6C");

                entity.HasOne(d => d.IdVacanteNavigation)
                    .WithMany(p => p.EstadoVacante)
                    .HasForeignKey(d => d.IdVacante)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__EstadoVac__IdVac__2180FB33");
            });

            modelBuilder.Entity<Modulo>(entity =>
            {
                entity.HasOne(d => d.IdSistemaNavigation)
                    .WithMany(p => p.Modulo)
                    .HasForeignKey(d => d.IdSistema)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Modulo_Sistema");
            });

            modelBuilder.Entity<ResponsableEmpresa>(entity =>
            {
                entity.HasOne(d => d.IdEmpresaNavigation)
                    .WithMany(p => p.ResponsableEmpresa)
                    .HasForeignKey(d => d.IdEmpresa)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Responsab__IdEmp__19DFD96B");

                entity.HasOne(d => d.IdTipoUsuarioNavigation)
                    .WithMany(p => p.ResponsableEmpresa)
                    .HasForeignKey(d => d.IdTipoUsuario)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Responsab__IdTip__1AD3FDA4");
            });

            modelBuilder.Entity<Rol>(entity =>
            {
                entity.HasOne(d => d.IdSistemaNavigation)
                    .WithMany(p => p.Rol)
                    .HasForeignKey(d => d.IdSistema)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Rol_Sistema");
            });

            modelBuilder.Entity<RolTransaccion>(entity =>
            {
                entity.HasKey(e => new { e.IdRol, e.IdTransaccion });

                entity.HasOne(d => d.IdRolNavigation)
                    .WithMany(p => p.RolTransaccion)
                    .HasForeignKey(d => d.IdRol)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_RolTransaccion_Rol");

                entity.HasOne(d => d.IdTransaccionNavigation)
                    .WithMany(p => p.RolTransaccion)
                    .HasForeignKey(d => d.IdTransaccion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_RolTransaccion_Transaccion");
            });

            modelBuilder.Entity<RolUsuario>(entity =>
            {
                entity.HasOne(d => d.IdRolNavigation)
                    .WithMany()
                    .HasForeignKey(d => d.IdRol)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_RolUsuario_Rol");

                entity.HasOne(d => d.IdUsuarioNavigation)
                    .WithMany()
                    .HasForeignKey(d => d.IdUsuario)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_RolUsuario_AspNetUsers");
            });

            modelBuilder.Entity<Transaccion>(entity =>
            {
                entity.HasOne(d => d.IdModuloNavigation)
                    .WithMany(p => p.Transaccion)
                    .HasForeignKey(d => d.IdModulo)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Transaccion_Modulo");

                entity.HasOne(d => d.IdPadreNavigation)
                    .WithMany(p => p.InverseIdPadreNavigation)
                    .HasForeignKey(d => d.IdPadre)
                    .HasConstraintName("FK_Transaccion_Transaccion");
            });

            modelBuilder.Entity<Vacante>(entity =>
            {
                entity.HasOne(d => d.IdEmpresaNavigation)
                    .WithMany(p => p.Vacante)
                    .HasForeignKey(d => d.IdEmpresa)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Vacante__IdEmpre__7F2BE32F");

                entity.HasOne(d => d.IdTipoVacanteNavigation)
                    .WithMany(p => p.Vacante)
                    .HasForeignKey(d => d.IdTipoVacante)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Vacante__IdVacan__00200768");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}