// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Unach.DA.Empleo.Persistencia.Core.Models
{
    public partial class TipoEstadoVacante
    {
        public TipoEstadoVacante()
        {
            EstadoVacante = new HashSet<EstadoVacante>();
        }

        [Key]
        public int Id { get; set; }
        public bool Nombre { get; set; }

        [InverseProperty("IdEstadoVacanteNavigation")]
        public virtual ICollection<EstadoVacante> EstadoVacante { get; set; }
    }
}