// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Unach.DA.Empleo.Persistencia.Core.Models
{
    public partial class TipoCapacitacion
    {
        public TipoCapacitacion()
        {
            Capacitacion = new HashSet<Capacitacion>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Nombre { get; set; }

        [InverseProperty("IdCapacitacionNavigation")]
        public virtual ICollection<Capacitacion> Capacitacion { get; set; }
    }
}