// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Unach.DA.Empleo.Persistencia.Core.Models
{
    public partial class TipoEstadoPostulacion
    {
        public TipoEstadoPostulacion()
        {
            EstadoPostulacion = new HashSet<EstadoPostulacion>();
        }

        [Key]
        [StringLength(50)]
        public string Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Nombre { get; set; }

        [InverseProperty("IdEstadoPostulacionNavigation")]
        public virtual ICollection<EstadoPostulacion> EstadoPostulacion { get; set; }
    }
}