// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Unach.DA.Empleo.Persistencia.Core.Models
{
    [Table("Transaccion", Schema = "Auth")]
    public partial class Transaccion
    {
        public Transaccion()
        {
            InverseIdPadreNavigation = new HashSet<Transaccion>();
            RolTransaccion = new HashSet<RolTransaccion>();
        }

        [Key]
        public int Id { get; set; }
        public int? IdPadre { get; set; }
        public int IdModulo { get; set; }
        [Required]
        [StringLength(250)]
        public string Titulo { get; set; }
        [Required]
        [StringLength(250)]
        public string Descripcion { get; set; }
        [Required]
        [StringLength(250)]
        public string Controlador { get; set; }
        [Required]
        [StringLength(250)]
        public string Accion { get; set; }
        [Required]
        [StringLength(250)]
        public string IconClass { get; set; }
        public int Orden { get; set; }
        public bool Estado { get; set; }
        public bool Visible { get; set; }
        [Required]
        [StringLength(15)]
        public string IdUsuarioAudd { get; set; }
        [Required]
        public string RolAudd { get; set; }
        [Required]
        [StringLength(50)]
        public string DireccionIpAudd { get; set; }
        [Required]
        [StringLength(250)]
        public string SistemaAudd { get; set; }
        public bool? Activo { get; set; }

        [ForeignKey("IdModulo")]
        [InverseProperty("Transaccion")]
        public virtual Modulo IdModuloNavigation { get; set; }
        [ForeignKey("IdPadre")]
        [InverseProperty("InverseIdPadreNavigation")]
        public virtual Transaccion IdPadreNavigation { get; set; }
        [InverseProperty("IdPadreNavigation")]
        public virtual ICollection<Transaccion> InverseIdPadreNavigation { get; set; }
        [InverseProperty("IdTransaccionNavigation")]
        public virtual ICollection<RolTransaccion> RolTransaccion { get; set; }
    }
}