// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Unach.DA.Empleo.Persistencia.Core.Models
{
    public partial class Vacante
    {
        public Vacante()
        {
            EstadoVacante = new HashSet<EstadoVacante>();
            Postulacion = new HashSet<Postulacion>();
        }

        [Key]
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public int IdTipoVacante { get; set; }
        [Required]
        [StringLength(100)]
        public string IdUsuarioAudd { get; set; }
        [Required]
        public string RolAudd { get; set; }
        [Required]
        [StringLength(50)]
        public string DireccionIpAudd { get; set; }
        [Required]
        [StringLength(250)]
        public string SistemaAudd { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaTransaccion { get; set; }
        public int? Plaza { get; set; }
        [StringLength(250)]
        public string Descripcion { get; set; }
        [StringLength(250)]
        public string Cargo { get; set; }
        [StringLength(250)]
        public string Cuidad { get; set; }
        [StringLength(250)]
        public string Sector { get; set; }
        [StringLength(250)]
        public string Contacto { get; set; }
        [StringLength(250)]
        public string TipoContrato { get; set; }
        [StringLength(250)]
        public string Parroquia { get; set; }
        [StringLength(250)]
        public string Telefono { get; set; }
        [StringLength(250)]
        public string CorreoElectronico { get; set; }
        [StringLength(250)]
        public string Instruccion { get; set; }
        public int IdTipoCarrera { get; set; }
        public string ConocimientosPrevios { get; set; }
        [StringLength(50)]
        public string Remuneracion { get; set; }
        public string Experiencia { get; set; }
        public string Actividades { get; set; }
        [StringLength(250)]
        public string Jornada { get; set; }
        [StringLength(250)]
        public string AreaExperiencia { get; set; }
        [StringLength(250)]
        public string AreaCapacitacion { get; set; }

        [ForeignKey("IdEmpresa")]
        [InverseProperty("Vacante")]
        public virtual Empresa IdEmpresaNavigation { get; set; }
        [ForeignKey("IdTipoVacante")]
        [InverseProperty("Vacante")]
        public virtual TipoVacante IdTipoVacanteNavigation { get; set; }
        [InverseProperty("IdVacanteNavigation")]
        public virtual ICollection<EstadoVacante> EstadoVacante { get; set; }
        [InverseProperty("IdVacanteNavigation")]
        public virtual ICollection<Postulacion> Postulacion { get; set; }
    }
}