// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Unach.DA.Empleo.Persistencia.Core.Models
{
    public partial class Vacante
    {
        public Vacante()
        {
            EstadoVacante = new HashSet<EstadoVacante>();
            Postulacion = new HashSet<Postulacion>();
        }

        [Key]
        public int IdV { get; set; }
        public int IdEmpresa { get; set; }
        public int IdVacante { get; set; }
        [Required]
        [StringLength(100)]
        public string IdUsuarioAudd { get; set; }
        [Required]
        public string RolAudd { get; set; }
        [Required]
        [StringLength(50)]
        public string DireccionlpAudd { get; set; }
        [Required]
        [StringLength(250)]
        public string SistemaAudd { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaTransaccion { get; set; }
        public int? Plaza { get; set; }
        [StringLength(250)]
        public string Descripcion { get; set; }
        [StringLength(250)]
        public string Cargo { get; set; }

        [ForeignKey("IdEmpresa")]
        [InverseProperty("Vacante")]
        public virtual Empresa IdEmpresaNavigation { get; set; }
        [ForeignKey("IdVacante")]
        [InverseProperty("Vacante")]
        public virtual TipoVacante IdVacanteNavigation { get; set; }
        [InverseProperty("IdVacanteNavigation")]
        public virtual ICollection<EstadoVacante> EstadoVacante { get; set; }
        [InverseProperty("IdVacanteNavigation")]
        public virtual ICollection<Postulacion> Postulacion { get; set; }
    }
}